language: rust
rust:
  - nightly
cache: cargo
env: >
  DATABASE_URL=postgres://postgres:@localhost:5432/diesel_testing
  RUST_TEST_THREADS=1
  SCHEMA_REGISTRY_PASSWORD=silly_password

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - which diesel || cargo install diesel_cli
  - diesel setup
  - diesel migration run

jobs:
  include:
    - script: cargo test --verbose
    - script: cargo clippy
