language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
env: >
  DATABASE_URL=postgres://postgres:@localhost:5432/diesel_testing
  RUST_TEST_THREADS=1
  SCHEMA_REGISTRY_PASSWORD=silly_password

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - which diesel || cargo install diesel_cli
  - rustup component add clippy rustfmt
  - diesel setup
  - diesel migration run

script:
  - cargo fmt -- --check
  - cargo test --verbose
  - cargo clippy
