language: rust
rust:
  - nightly
cache: cargo
env: >
  DATABASE_URL=postgres://postgres:@localhost:5432/diesel_testing
  PORT=22000
  RUST_TEST_THREADS=1
  SCHEMA_REGISTRY_PASSWORD=silly_password
  SENTRY_URL="https://1234@sentry.dev/1"

services:
  - postgresql
before_script:
  - cargo install diesel_cli
  - diesel setup
  - diesel migration run 
